# Generated by Django 3.0.4 on 2020-04-18 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('transcription', models.CharField(max_length=255)),
                ('definitions', models.CharField(max_length=255)),
                ('translations', models.CharField(max_length=255)),
                ('examples', models.CharField(max_length=255)),
                ('knowledge', models.CharField(choices=[('1', 'Fail'), ('2', 'Hard'), ('3', 'Good'), ('4', 'Easy')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
