# Generated by Django 3.0.4 on 2020-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userword',
            name='user',
        ),
        migrations.AlterField(
            model_name='userword',
            name='definitions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userword',
            name='examples',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userword',
            name='transcription',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userword',
            name='translations',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
