# Generated by Django 3.0.4 on 2020-04-18 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0002_auto_20200418_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userword',
            name='definitions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userword',
            name='examples',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
