# Generated by Django 3.0.4 on 2020-04-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20200418_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userword',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='user',
        ),
    ]
