# Generated by Django 3.0.4 on 2020-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20200429_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='transcription',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
