# Generated by Django 3.0.4 on 2020-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_userword_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='definitions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userword',
            name='examples',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userword',
            name='knowledge',
            field=models.CharField(choices=[('1', 'Fail'), ('2', 'Hard'), ('3', 'Good'), ('4', 'Easy')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userword',
            name='translations',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
